# Generated by Django 5.0 on 2023-12-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
