# Generated by Django 5.0 on 2024-01-16 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address_line_2',
            new_name='zip_code',
        ),
    ]
