# Generated by Django 5.0 on 2024-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_address_line_2_order_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreteSedex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep_inicial', models.CharField(max_length=8)),
                ('cep_final', models.CharField(max_length=8)),
                ('peso_maximo', models.CharField(max_length=10)),
                ('preco_frete', models.FloatField()),
            ],
        ),
    ]
