# Generated by Django 5.0 on 2024-01-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_fretesedex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fretesedex',
            name='preco_frete',
            field=models.CharField(max_length=10),
        ),
    ]
