# Generated by Django 5.0 on 2024-01-19 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_fretesedex_preco_frete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreteSedex',
        ),
    ]
